
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 67
#define YY_END_OF_BUFFER 68
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[259] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,   68,   66,
        1,    2,    2,   22,   53,   20,   66,   16,   28,    8,
       24,    9,   19,   66,   10,   47,   47,    3,   18,    7,
       13,   52,   17,   30,    4,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   14,
       66,   25,   58,   56,   56,   57,   55,   63,   64,   63,
       63,   61,   60,   60,    2,   21,    6,    0,   29,   29,
       44,   45,   62,   59,    0,   48,   48,   45,   47,    0,
        0,   15,   11,   12,    0,   51,   51,   52,   52,    0,
       31,   31,   52,   52,   52,   52,   52,   52,   52,   52,

       52,   52,   52,   52,   44,   34,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   23,   26,
       26,   56,   55,   54,   64,   65,   60,    0,   46,   46,
        0,   45,    0,    0,   45,   47,   47,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   33,   52,   52,
       52,   36,   44,    0,   52,   52,   52,   52,   52,   52,
       52,   35,    0,    0,   45,    0,   45,   38,   52,   52,
       52,   52,   52,   32,   52,   52,    0,   42,   52,   52,
        0,   52,   52,   52,   52,   52,   52,   52,   52,    0,
       52,   52,   52,   52,    0,   52,   52,    0,   52,   52,

       52,   52,   52,   52,   52,    0,   52,   52,   52,   52,
        0,   52,    0,   52,   50,   52,   39,    0,   52,   52,
       37,    0,   52,   43,    5,    0,   49,   49,   52,    0,
       52,    0,   52,    0,    0,   52,    0,    0,    0,   52,
        0,    0,    0,   40,    0,    0,   41,    0,    0,    0,
        0,    0,    0,    0,    0,   27,   27,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    4,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    6,    7,    8,    1,    1,    9,   10,    1,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       22,   20,   20,   20,   20,   20,   20,    1,   23,   24,
       25,   26,    1,    1,   27,   28,   29,   28,   30,   28,
       31,   31,   32,   31,   31,   33,   34,   35,   36,   37,
       31,   31,   31,   38,   39,   31,   31,   40,   31,   31,
       41,   42,   43,    1,   44,    1,   45,   46,   47,   48,

       49,   50,   51,   52,   53,   54,   55,   56,   57,   58,
       59,   60,   54,   61,   62,   63,   64,   65,   66,   67,
       68,   54,   69,   70,   71,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[72] =
    {   0,
        1,    2,    3,    2,    2,    2,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    4,    4,
        4,    4,    1,    1,    1,    1,    4,    4,    4,    4,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        1,    1,    1,    2,    4,    4,    4,    4,    4,    4,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    1,    1,
        1
    } ;

static yyconst flex_int16_t yy_base[266] =
    {   0,
        0,    0,   69,   70,   76,   77,   80,   81,  711,  712,
      712,  712,  707,  683,  712,  712,  694,  712,   89,  712,
      671,  712,  667,   77,   87,  111,   36,  712,  657,  650,
      648,  104,  712,  116,  133,  177,   97,   85,   84,  105,
       43,  113,  114,  106,  131,  142,  145,  125,  155,  712,
      602,  647,  712,  712,  667,  712,  181,  712,  712,  644,
      626,  712,  712,  594,  712,  712,  712,  215,  712,  584,
      712,  243,  712,  712,  222,  712,  568,  291,  145,  236,
      213,  712,  712,  712,  264,  712,  567,   68,  146,  272,
      712,  516,  154,  192,  220,  226,  225,  230,  239,  243,

      200,  244,  229,  256,  257,  247,  263,  266,  271,  292,
      286,  276,  280,  293,  267,  283,  296,  287,  712,  712,
      484,  712,  712,  712,  712,  712,  712,  356,  712,  499,
      349,    0,  358,  362,  383,  388,  393,  355,  305,  363,
      359,  364,  370,  379,  374,  387,  383,  314,  390,  375,
      380,  394,  386,  474,  395,  401,  400,  408,  418,  407,
      414,  413,  442,  464,  485,  473,  494,  417,  462,  449,
      450,  461,  465,  468,  469,  472,  443,  475,  478,  479,
      397,  496,  493,  484,  497,  487,  492,  500,  513,  388,
      504,  508,  514,  527,  352,  517,  518,  355,  530,  524,

      531,  537,  542,  541,  547,  363,  546,  550,  553,  563,
      323,  570,  305,  567,  615,  571,  564,  306,  578,  574,
      579,  261,  587,  712,  582,  647,  712,  269,  625,  227,
      595,  191,  596,  216,  208,  607,  181,  167,  194,  608,
      164,  151,  179,  712,  149,  166,  712,  152,  143,  127,
      113,  109,   75,  659,  675,  712,   85,  712,  686,  690,
      694,  697,  701,  705,   83
    } ;

static yyconst flex_int16_t yy_def[266] =
    {   0,
      258,    1,  259,  259,  260,  260,  261,  261,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,   26,  258,  258,  258,
      258,  262,  258,  258,  262,  262,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,  258,
      258,  263,  258,  258,  258,  258,  264,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,   26,  258,
      265,  258,  258,  258,  258,  258,  258,   36,   36,  258,
      258,  258,   36,   36,   36,   36,   36,   36,   36,   36,

       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,   78,  258,  258,  258,  258,  258,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,  258,   36,   36,   36,   36,   36,   36,
       36,   36,  258,  258,  258,  258,  258,   36,   36,   36,
       36,   36,   36,   36,   36,   36,  258,   36,   36,   36,
      258,   36,   36,   36,   36,   36,   36,   36,   36,  258,
       36,   36,   36,   36,  258,   36,   36,  258,   36,   36,

       36,   36,   36,   36,   36,  258,   36,   36,   36,   36,
      258,   36,  258,   36,   36,   36,   36,  258,   36,   36,
       36,  258,   36,  258,   36,  258,  258,  258,   36,  258,
       36,  258,   36,  258,  258,   36,  258,  258,  258,   36,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,    0,  258,  258,
      258,  258,  258,  258,  258
    } ;

static yyconst flex_int16_t yy_nxt[784] =
    {   0,
       10,   11,   12,   11,   13,   11,   14,   15,   16,   17,
       18,   19,   20,   21,   22,   23,   24,   25,   26,   27,
       27,   27,   28,   29,   30,   31,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       33,   10,   34,   35,   32,   36,   37,   38,   39,   40,
       41,   32,   42,   32,   32,   32,   43,   32,   44,   45,
       46,   47,   48,   32,   49,   32,   32,   32,   50,   51,
       52,   54,   54,   55,   55,  258,   56,   56,   59,   59,
       60,   60,   63,   63,   64,   64,  137,  256,   61,   61,
       68,   69,   68,   70,   68,   72,   72,   72,   72,   73,

      254,  105,  258,   89,   74,   85,   86,   85,   87,   85,
       57,   57,   75,   76,   75,   77,   75,   90,   91,   90,
       92,   90,   88,   88,   88,   88,   89,   78,   89,   79,
       79,   79,   79,   98,   85,   86,   85,   87,   85,   99,
       80,   95,   89,   89,   89,   89,  253,  252,   96,  100,
       81,   88,   88,   88,   88,   97,  251,   89,  109,   80,
      101,  102,  106,  103,   89,   89,   89,  110,  104,  107,
      108,   89,   89,   89,   89,  111,  250,   81,   85,   86,
       85,   87,   85,   89,  258,   89,  112,  249,  124,   89,
      113,   89,  117,  114,  248,   88,   88,   88,   88,  118,

       89,  247,   89,   89,   89,   89,   89,  115,  246,  245,
      116,  258,  138,   89,   89,   89,   68,   69,   68,   70,
       68,  244,  124,   75,   76,   75,   77,   75,  243,  242,
      124,  136,  136,  136,  136,   93,  241,   94,  124,  239,
      139,  124,  238,  124,  128,  129,  128,  130,  128,  134,
       89,  134,   89,  237,  135,  135,  135,  135,  146,  235,
       89,   72,   72,   72,   72,   85,   86,   85,   87,   85,
      141,  227,  131,   90,   91,   90,   92,   90,   89,  143,
       89,  140,  142,   89,   89,   89,   89,   89,   89,  148,
       89,  131,  128,  129,  128,  130,  128,   89,  145,   89,

      144,   89,   89,   89,   89,   89,  147,   89,  154,  132,
      132,  132,  132,  149,   89,   89,   89,   89,  232,  150,
      133,   89,  151,   89,   89,   89,   89,  159,  152,   89,
      153,   89,  155,  156,   89,  160,   89,  230,   89,  133,
       89,   89,  157,   89,   89,   89,   89,  162,  158,  169,
       89,   89,   89,   89,   89,  161,   89,  128,  129,  128,
      130,  128,  164,   89,  164,   89,  224,  165,  165,  165,
      165,  166,   89,  166,   89,  222,  167,  167,  167,  167,
      135,  135,  135,  135,  128,  129,  128,  130,  128,   75,
       76,   75,   77,   75,   75,   76,   75,   77,   75,  177,

      218,  135,  135,  135,  135,  213,  136,  136,  136,  136,
      168,  153,  211,   89,  172,   89,  153,   89,  173,   89,
      206,   89,   89,   89,   89,  170,  171,  174,   89,  175,
       89,  176,   89,  153,   89,   89,  178,   89,  179,   89,
       89,   89,  180,   89,   89,   89,   89,   89,   89,  182,
       89,  183,   89,   89,   89,   89,  185,  198,   89,   89,
       89,   89,  153,  184,  186,   89,   89,   89,   89,  189,
      187,   89,   89,   89,   89,   89,   89,   89,   89,  195,
      190,  188,  165,  165,  165,  165,  128,  129,  128,  130,
      128,  167,  167,  167,  167,  128,  129,  128,  130,  128,

      181,  129,  191,  165,  165,  165,  165,   89,   89,   89,
       89,  153,  167,  167,  167,  167,  153,  163,   91,   89,
       89,   89,   89,   89,  192,  153,   89,   89,   89,   89,
       89,  193,   89,   89,  194,   89,   89,   89,  196,  197,
      199,  153,   89,  201,  200,  202,  204,   89,  210,  203,
       89,   89,   89,   89,   89,   89,   89,   89,   89,  205,
       89,  207,   89,  208,   89,  209,   89,  212,   89,   86,
       76,   89,   89,   89,   89,   89,   89,   89,   89,  153,
      214,  215,   89,  221,   89,   89,   69,   89,   89,   89,
       89,   89,  217,  153,  216,   89,  127,   89,  153,   89,

       89,   89,   89,  153,   89,   89,   89,   89,   89,  219,
       89,   89,  153,  220,  223,  225,  226,  227,  226,  228,
      226,   89,   89,   89,   89,   89,  153,   89,   89,   89,
       89,   89,  231,  233,   89,  229,   89,   89,   89,   89,
       89,  234,   89,  126,  153,   89,  125,   89,  226,  227,
      226,  228,  226,   89,   89,   89,   89,  240,  236,  153,
      255,  256,  255,  257,  255,   89,   89,   89,   89,  122,
      121,  119,   84,   89,   83,   89,  255,  256,  255,  257,
      255,   82,   71,   89,   71,   89,   53,   53,   53,   53,
       58,   58,   58,   58,   62,   62,   62,   62,   89,   89,

       89,  120,  120,   67,  120,  123,  123,   66,  123,   65,
      258,    9,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258
    } ;

static yyconst flex_int16_t yy_chk[784] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    4,    3,    4,   27,    3,    4,    5,    6,
        5,    6,    7,    8,    7,    8,  265,  257,    5,    6,
       19,   19,   19,   19,   19,   24,   24,   24,   24,   25,

      253,   41,   27,   41,   25,   32,   32,   32,   32,   32,
        3,    4,   26,   26,   26,   26,   26,   34,   34,   34,
       34,   34,   32,   32,   32,   32,   88,   26,   88,   26,
       26,   26,   26,   38,   35,   35,   35,   35,   35,   39,
       26,   37,   39,   38,   39,   38,  252,  251,   37,   40,
       26,   35,   35,   35,   35,   37,  250,   37,   43,   26,
       40,   40,   42,   40,   44,   40,   44,   44,   40,   42,
       42,   42,   43,   42,   43,   45,  249,   26,   36,   36,
       36,   36,   36,   48,   79,   48,   46,  248,   57,   45,
       46,   45,   48,   47,  246,   36,   36,   36,   36,   49,

       46,  245,   46,   47,   89,   47,   89,   47,  243,  242,
       47,   79,   93,   49,   93,   49,   68,   68,   68,   68,
       68,  241,   57,   75,   75,   75,   75,   75,  239,  238,
       57,   81,   81,   81,   81,   36,  237,   36,   57,  235,
       94,   57,  234,   57,   72,   72,   72,   72,   72,   80,
       94,   80,   94,  232,   80,   80,   80,   80,  101,  230,
      101,   72,   72,   72,   72,   85,   85,   85,   85,   85,
       96,  228,   72,   90,   90,   90,   90,   90,   95,   98,
       95,   95,   97,   97,   96,   97,   96,  103,   98,  103,
       98,   72,   78,   78,   78,   78,   78,   99,  100,   99,

       99,  100,  102,  100,  102,  106,  102,  106,  110,   78,
       78,   78,   78,  104,  104,  105,  104,  105,  222,  105,
       78,  107,  107,  107,  108,  115,  108,  115,  108,  109,
      109,  109,  111,  112,  112,  116,  112,  218,  113,   78,
      113,  116,  113,  116,  111,  118,  111,  118,  114,  139,
      110,  114,  110,  114,  117,  117,  117,  128,  128,  128,
      128,  128,  131,  139,  131,  139,  213,  131,  131,  131,
      131,  133,  148,  133,  148,  211,  133,  133,  133,  133,
      134,  134,  134,  134,  135,  135,  135,  135,  135,  136,
      136,  136,  136,  136,  137,  137,  137,  137,  137,  147,

      206,  135,  135,  135,  135,  198,  136,  136,  136,  136,
      138,  140,  195,  138,  143,  138,  141,  141,  143,  141,
      190,  140,  142,  140,  142,  142,  142,  144,  143,  145,
      143,  146,  145,  150,  145,  150,  149,  144,  151,  144,
      151,  147,  152,  147,  153,  146,  153,  146,  149,  155,
      149,  156,  152,  155,  152,  155,  158,  181,  157,  156,
      157,  156,  161,  157,  159,  160,  158,  160,  158,  160,
      159,  162,  161,  162,  161,  168,  159,  168,  159,  177,
      163,  159,  164,  164,  164,  164,  165,  165,  165,  165,
      165,  166,  166,  166,  166,  167,  167,  167,  167,  167,

      154,  130,  171,  165,  165,  165,  165,  170,  171,  170,
      171,  170,  167,  167,  167,  167,  169,  121,   92,  172,
      169,  172,  169,  173,  172,  173,  174,  175,  174,  175,
      176,  175,  176,  178,  176,  178,  179,  180,  179,  180,
      182,  183,  184,  185,  184,  186,  188,  186,  194,  187,
      187,  183,  187,  183,  182,  185,  182,  185,  188,  189,
      188,  191,  191,  192,  191,  193,  192,  197,  192,   87,
       77,  189,  193,  189,  193,  196,  197,  196,  197,  196,
      199,  200,  200,  210,  200,  194,   70,  194,  199,  201,
      199,  201,  203,  201,  202,  202,   64,  202,  205,  204,

      203,  204,  203,  204,  207,  205,  207,  205,  208,  207,
      208,  209,  208,  209,  212,  214,  215,  215,  215,  215,
      215,  210,  217,  210,  217,  214,  219,  214,  212,  216,
      212,  216,  220,  223,  220,  216,  219,  221,  219,  221,
      225,  229,  225,   61,  233,  223,   60,  223,  226,  226,
      226,  226,  226,  231,  233,  231,  233,  236,  231,  240,
      254,  254,  254,  254,  254,  236,  240,  236,  240,   55,
       52,   51,   31,  215,   30,  215,  255,  255,  255,  255,
      255,   29,   23,  229,   21,  229,  259,  259,  259,  259,
      260,  260,  260,  260,  261,  261,  261,  261,  262,  262,

      262,  263,  263,   17,  263,  264,  264,   14,  264,   13,
        9,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "gocompiler.l"
#line 3 "gocompiler.l"
    #include <stdio.h>
    #include <stdlib.h>
    #include <string.h>

    int line=1;
    int column=1;
    int line_begin=1;
    int column_begin=1;
    int print=0;
    char* strLitAux;
    char* idaux;
    int invalid_escape;
    int end_of_file=0;
    int missing_semicolon=0;




#line 729 "lex.yy.c"

#define INITIAL 0
#define STRLIT 1
#define MULTILINECOMENT 2
#define ONELINECOMENT 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 83 "gocompiler.l"


#line 917 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 259 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 712 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 85 "gocompiler.l"
{column+=yyleng;}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 86 "gocompiler.l"
{line++;column=1;} // carriage return - representa o fim de uma linha e deixa o cursor no inicio dessa mesma linha ,line feed - move o cursor para a proxima linha, end of line - combinacao dos dois
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 88 "gocompiler.l"
{if(print==1) printf("SEMICOLON\n");column+=yyleng;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 89 "gocompiler.l"
{if(print==1) printf("BLANKID\n");column+=yyleng;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 90 "gocompiler.l"
{if(print==1) printf("PACKAGE\n");column+=yyleng;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 92 "gocompiler.l"
{if(print==1) printf("AND\n");column+=yyleng;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 93 "gocompiler.l"
{if(print==1) printf("ASSIGN\n");column+=yyleng;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 94 "gocompiler.l"
{if(print==1) printf("STAR\n");column+=yyleng;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 95 "gocompiler.l"
{if(print==1) printf("COMMA\n");column+=yyleng;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 96 "gocompiler.l"
{if(print==1) printf("DIV\n");column+=yyleng;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 97 "gocompiler.l"
{if(print==1) printf("EQ\n");column+=yyleng;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 98 "gocompiler.l"
{if(print==1) printf("GE\n");column+=yyleng;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 99 "gocompiler.l"
{if(print==1) printf("GT\n");column+=yyleng;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 100 "gocompiler.l"
{if(print==1) printf("LBRACE\n");column+=yyleng;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 101 "gocompiler.l"
{if(print==1) printf("LE\n");column+=yyleng;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 102 "gocompiler.l"
{if(print==1) printf("LPAR\n");column+=yyleng;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 103 "gocompiler.l"
{if(print==1) printf("LSQ\n");column+=yyleng;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 104 "gocompiler.l"
{if(print==1) printf("LT\n");column+=yyleng;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 105 "gocompiler.l"
{if(print==1) printf("MINUS\n");column+=yyleng;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 106 "gocompiler.l"
{if(print==1) printf("MOD\n");column+=yyleng;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 107 "gocompiler.l"
{if(print==1) printf("NE\n");column+=yyleng;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 108 "gocompiler.l"
{if(print==1) printf("NOT\n");column+=yyleng;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 109 "gocompiler.l"
{if(print==1) printf("OR\n");column+=yyleng;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 110 "gocompiler.l"
{if(print==1) printf("PLUS\n");column+=yyleng;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 112 "gocompiler.l"
{if(print==1) printf("RBRACE\n");
                            column+=yyleng;
                            if(print==1) printf("SEMICOLON\n");}
	YY_BREAK
case 26:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 116 "gocompiler.l"
{if(print==1) printf("RBRACE\n");
                            column+=yyleng;}
	YY_BREAK
case 27:
/* rule 27 can match eol */
YY_RULE_SETUP
#line 118 "gocompiler.l"
{if(print==1) printf("RBRACE\n");
                            if(print==1) printf("SEMICOLON\n");
                            column+=yyleng;
                            missing_semicolon=1;} 
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 122 "gocompiler.l"
{if(print==1) printf("RPAR\n");
                            column+=yyleng;}
	YY_BREAK
case 29:
/* rule 29 can match eol */
YY_RULE_SETUP
#line 124 "gocompiler.l"
{if(print==1) printf("RPAR\n");
                            if(print==1) printf("SEMICOLON\n");
                            column+=yyleng;
                        missing_semicolon=1;}                            
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 128 "gocompiler.l"
{if(print==1) printf("RSQ\n");
                            column+=yyleng;
                        missing_semicolon=1;}
	YY_BREAK
case 31:
/* rule 31 can match eol */
YY_RULE_SETUP
#line 131 "gocompiler.l"
{if(print==1) printf("RSQ\n");
                            if(print==1) printf("SEMICOLON\n");
                            column+=yyleng;
                            missing_semicolon=1;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 135 "gocompiler.l"
{if(print==1) printf("ELSE\n");column+=yyleng;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 136 "gocompiler.l"
{if(print==1) printf("FOR\n");column+=yyleng;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 137 "gocompiler.l"
{if(print==1) printf("IF\n");column+=yyleng;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 138 "gocompiler.l"
{if(print==1) printf("VAR\n");column+=yyleng;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 139 "gocompiler.l"
{if(print==1) printf("INT\n");column+=yyleng;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 140 "gocompiler.l"
{if(print==1) printf("FLOAT32\n");column+=yyleng;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 141 "gocompiler.l"
{if(print==1) printf("BOOL\n");column+=yyleng;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 142 "gocompiler.l"
{if(print==1) printf("STRING\n");column+=yyleng;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 143 "gocompiler.l"
{if(print==1) printf("PRINT\n");column+=yyleng;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 144 "gocompiler.l"
{if(print==1) printf("PARSEINT\n");column+=yyleng;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 145 "gocompiler.l"
{if(print==1) printf("FUNC\n");column+=yyleng;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 146 "gocompiler.l"
{if(print==1) printf("CMDARGS\n");column+=yyleng;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 147 "gocompiler.l"
{if(print==1) printf("RESERVED(%s)\n",yytext);column+=yyleng;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 149 "gocompiler.l"
{if(print==1) printf("REALLIT(%s)\n",yytext);column+=yyleng;}
	YY_BREAK
case 46:
/* rule 46 can match eol */
YY_RULE_SETUP
#line 150 "gocompiler.l"
{if(print==1) printf("REALLIT(%s)\n",yytext);
                                if(print==1) printf("SEMICOLON\n");
                                line++;
                                column=1;
                                missing_semicolon=1;
                                }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 157 "gocompiler.l"
{if(print==1) printf("INTLIT(%s)\n",yytext);column+=yyleng;}
	YY_BREAK
case 48:
/* rule 48 can match eol */
YY_RULE_SETUP
#line 158 "gocompiler.l"
{idaux=yytext;
                                int i=0;
                                while(yytext[i]!='\0'&&yytext[i]!=' '&&yytext[i]!='\n'){
                                    idaux[i]=yytext[i];
                                    i++;
                                }
                                idaux[i]='\0';
                                if(print==1) printf("INTLIT(%s)\n",idaux);
                                if(print==1) printf("SEMICOLON\n");
                                line++;
                                column=1;
                                missing_semicolon=1;
                                }
	YY_BREAK
case 49:
/* rule 49 can match eol */
YY_RULE_SETUP
#line 172 "gocompiler.l"
{
                                if(print==1) printf("RETURN\n");
                                if(print==1) printf("SEMICOLON\n");
                                line++;
                                column=1;
                                missing_semicolon=1;
                                }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 179 "gocompiler.l"
{if(print==1) printf("RETURN\n");column+=yyleng;}
	YY_BREAK
case 51:
/* rule 51 can match eol */
YY_RULE_SETUP
#line 181 "gocompiler.l"
{
                                idaux=yytext;
                                int i=0;
                                while(yytext[i]!='\0'&&yytext[i]!=' '&&yytext[i]!='\n'){
                                    idaux[i]=yytext[i];
                                    i++;
                                }
                                idaux[i]='\0';
                                if(print==1) printf("ID(%s)\n",idaux);
                                if(print==1) printf("SEMICOLON\n");
                                line++;
                                column=1;
                                }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 194 "gocompiler.l"
{if(print==1) printf("ID(%s)\n",yytext);column+=yyleng;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 200 "gocompiler.l"
{BEGIN STRLIT;
            strLitAux=yytext; 
            invalid_escape=0;
            line_begin=line;
            column_begin=column;
            column+=yyleng;
            }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 208 "gocompiler.l"
{column+=yyleng;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 210 "gocompiler.l"
{
                            invalid_escape=1;
                            printf("Line %d, column %d: invalid escape sequence (%s)\n", line, column, yytext);
                            column+=yyleng;
                            }
	YY_BREAK
case 56:
/* rule 56 can match eol */
YY_RULE_SETUP
#line 217 "gocompiler.l"
{line++;column=1;
                    printf("Line %d, column %d: unterminated string literal\n", line_begin, column_begin);
                    BEGIN 0; // volta ao estado inicial 
                    }
	YY_BREAK
case YY_STATE_EOF(STRLIT):
#line 222 "gocompiler.l"
{
                    column+=yyleng;
                    printf("Line %d, column %d: unterminated string literal\n", line_begin, column_begin);
                    BEGIN 0; // volta ao estado inicial 
                    }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 228 "gocompiler.l"
{
                    column+=yyleng;
                    if (print==1){
                        if(invalid_escape==0){
                            printf("STRLIT(%s)\n",strLitAux);
                        }
                        
                    }
                    BEGIN 0;
                    }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 238 "gocompiler.l"
{column+=yyleng;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 240 "gocompiler.l"
{BEGIN ONELINECOMENT;column+=2;}
	YY_BREAK
case 60:
/* rule 60 can match eol */
YY_RULE_SETUP
#line 241 "gocompiler.l"
{column=1;line++;BEGIN 0;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 242 "gocompiler.l"
{column+=yyleng;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 244 "gocompiler.l"
{BEGIN MULTILINECOMENT;line_begin=line;column_begin=column;column+=2;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 246 "gocompiler.l"
{column+=yyleng;}
	YY_BREAK
case 64:
/* rule 64 can match eol */
YY_RULE_SETUP
#line 247 "gocompiler.l"
{column=1;line++;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 248 "gocompiler.l"
{BEGIN 0;column+=yyleng;}
	YY_BREAK
case YY_STATE_EOF(MULTILINECOMENT):
#line 249 "gocompiler.l"
{printf("Line %d, column %d: unterminated comment\n",line_begin,column_begin);BEGIN 0;}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(ONELINECOMENT):
#line 250 "gocompiler.l"
{if(end_of_file==0){
                        printf("EOGFFFFFFFFFFF\n");
                        end_of_file=1;
                        return 0;
                    }}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 255 "gocompiler.l"
{printf("Line %d, column %d: illegal character (%s)\n",line,column,yytext);column+=yyleng;};
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 258 "gocompiler.l"
ECHO;
	YY_BREAK
#line 1442 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 259 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 259 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 258);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n, i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 258 "gocompiler.l"


int main(int argc, char *argv[]){
    if(strcmp(argv[1],"-l")==0){
		print=1;
        yylex();
    }
	return 0;
}

int yywrap(){
	return 1;
}

void yyerror(char *s){
    printf("Line %d, col %d: %s: %s\n",line,(int)(column-(int)yyleng),s,yytext);
}
